version: '3.8'
services:
  postgresql:
    image: postgres:13.1-alpine
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - app-network
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - '5342:80'
      - '5341:5341'
    volumes:
      - ./data/seq:/data
    environment:
      ACCEPT_EULA: 'Y'
      SEQ_CACHE_SYSTEMRAMTARGET: "0.2"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

# docker-compose up -d redis rabbitmq postgresql seq
# service docker start
